### ISSUE TITLE
v4.0 Final Features

### ISSUE THREAD

**Issue by oLokem** [edward-dunton/miorga-fight#25]
#### Features:
- [x] Testing of new multiplayer UI
- [x] Regia transition hitboxes
- Tree foliage for Holyree:
   - [x] Graphics
   - [x] Implementation
 - Tailor character selection:
   - [x] Centralised animations
   - [x] Action set overlays
   - [x] Implementation

#### Bugs:

R - Regression

 - [x] Tailor action tree needs fix for riposte - R
 - [x] Tailor character selection doesn't line up - R 
 - [x] P1 always shows as connecting - R
 - [x] Tailor high alt has halt - update action tree - R
 - [x] Dark grass 3 wave animation incorrect frame - R
 - [x] Parry bug - when Regia is parrying - however was attack index out of range

**Comment by eddy-dunton** [comment]
Tailor blood added in ee524b0

**Comment by eddy-dunton** [comment]
`E 0:06:37.488   void System.ThrowHelper.ThrowArgumentOutOfRange_IndexException(): System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.`

`Parameter name: index
  <C++ Error>   Unhandled exception
  <C++ Source>  :0 @ void System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()()
  <Stack Trace> :0 @ void System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()()
                :0 @ MiorgaFight.Action System.Collections.Generic.List1[[MiorgaFight.Action, Miorga Fight, Version=1.0.7545.35544, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 )()
                Player.cs:420 @ void MiorgaFight.Player.Parried_ByIndex_(Int32 , Int32 )()`
