### ISSUE TITLE
Performing Regia High Main too close to enemy causes him to slide down 

### ISSUE THREAD

**Issue by eddy-dunton** [edward-dunton/miorga-fight#7]
Only testing in MP
Needs more testing

**Comment by eddy-dunton** [comment]
Most likely will have to be fixed in code

**Comment by oLokem** [comment]
I noticed the same thing today in local, if that helps

**Comment by eddy-dunton** [comment]
Ye cheers
I think it's the physics system causing it
Think I will just have to reset the players y value every frame
